### ISSUE TITLE
StackOverflowError 

### ISSUE THREAD

**Issue by mlotysz** [mhjort/clj-gatling-example#2]
I'm trying to generate heavy load for some backend system but unfortunately I was hit by StackOverflowError. I fork your project to reproduce my bug na dhere it is.

```
clj-gatling-example (master)]$ lein run metrics 2800 1
Exception in thread "main" java.lang.StackOverflowError, compiling:(/private/var/folders/f5/k0cgb1rs0hldwslr_l5hlpkc0000gn/T/form-init8067742416466387465.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.StackOverflowError
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$map$fn__4789.invoke(core.clj:2648)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$map$fn__4789.invoke(core.clj:2648)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$map$fn__4789.invoke(core.clj:2648)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
...
```

Do you have any clues what is core problem here? I'd like to help solve it if I can.

**Comment by mlotysz** [comment]
I think: https://github.com/mhjort/clj-gatling/issues/40 better fits this problem.
